config/routes.rb
Rails.application.routes.draw do
  root 'invoices#index'
  resources :invoices
  resources :products
  resources :customers
  resources :invoice_styles

  get 'invoices/:id/print_pdf', to: "invoices#print_pdf", as: "print_invoice"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions, only: [:create, :destroy]

end

app/models/invoice.rb
require_relative "#{Rails.root}/core/invoice-printer/lib/invoice_writer"

class Invoice < ActiveRecord::Base
  include ApplicationHelper

  belongs_to :customer
  has_many :line_items, :inverse_of => :invoice
  has_many :products, :through => :line_items
  belongs_to :invoice_style
  accepts_nested_attributes_for :line_items, allow_destroy: true

  validates :tax_rate, numericality: {greater_than_or_equal_to: 0.0}
  validates :customer, :presence => true

  @@invoice_writer = InvoiceWriter.new

  def sub_total
    sum = 0
    line_items.each do |line_item|
      sum += line_item.total
    end
    return sum.round(2)
  end

  def tax_amount
    return (sub_total * (tax_rate / 100)).round(2)
  end

  def general_total
    return (sub_total + tax_amount).round(2)
  end

  def get_data_in_hash_format
      return {
        'date' => date.strftime("%m/%d/%Y"),
        'time' => time.strftime("%H:%M"),
        'buyer-name' => customer.name,
        'buyer-address' => customer.address,
        'buyer-tax_office' => customer.tax_office,
        'buyer-tax_office_no' => customer.tax_office_no,
        'line_items' =>
           {'description' => line_items.map {|l| l.product.description},
            'quantity' => line_items.map {|l| l.quantity.to_s},
            'unit' => line_items.map {|l| l.product.unit},
            'unit_price' => line_items.map {|l| format_price(l.product.unit_price)},
            'line_total' => line_items.map {|l| format_price(l.total)}},
        'total' => format_price(sub_total),
        'tax_rate' => format_price(tax_rate),
        'tax_amount' => format_price(tax_amount),
        'general_total' => format_price(general_total),
        'general_total_reading' => get_price_reading(general_total)
      }
  end

  def print_pdf(output_file_location)
    @@invoice_writer.generate(get_data_in_hash_format(), invoice_style.get_config(), output_file_location)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy, :print_pdf]
  before_action :set_others

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @invoice.line_items.build
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)
    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Fatura başarıyla oluşturuldu.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Fatura başarıyla güncellendi.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Fatura başarıyla silindi.' }
      format.json { head :no_content }
    end
  end

  def print_pdf
    output_file_location = "#{Rails.root}/public/output.pdf"
    @invoice.print_pdf(output_file_location)
    send_file(
      output_file_location,
      filename: "output.pdf",
      type: "application/pdf"
    )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    def set_others
      @customers = Customer.all
      @products = Product.all
      @invoice_styles = InvoiceStyle.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      invoice_params = params.require(:invoice).permit(:date, :time, :tax_rate, :customer_id, :invoice_style_id,
                                      line_items_attributes: [:id, :product_id, :quantity])
      line_items_attributes = invoice_params['line_items_attributes']
      if line_items_attributes
        line_items_attributes.values.each do |line_item_attr|
          line_item_attr['_destroy'] = '1' if line_item_attr.length == 1 and line_item_attr.keys.first == 'id'
        end
      end
      invoice_params
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h4>

      <ul>
        <% @invoice.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for(@invoice) do |f| %>
  <div class="row">
    <label>Tarih</label>
    <%= f.date_select :date %>
  </div>
  <div class="row">
    <label>Saat</label>
    <%= f.time_select :time %>
  </div>
  <div class="row">
    <label>Müşteri</label>
    <%= f.select(:customer_id, @customers.collect {|c| [c.name, c.id]}) %>
  </div>
  <div class="row">
    <label>Vergi Oranı</label>
    <%= f.text_field :tax_rate %>
  </div>
  <div class="line_items">
    <label>Satır Öğeleri</label><br/>
    <button type="button" onclick="addRow()">Satır Ekle</button>
    <button type="button" onclick="deleteRow()">Satır Sil</button>
  </div>
  <table id="line_item_form">
    <tr>
      <th>Ürün</th>
      <th>Adet</th>
    </tr>
    <%= f.fields_for :line_items do |lf| %>
      <tr>
        <td><%= lf.select(:product_id, @products.collect {|p| [p.description, p.id]}) %></td>
        <td><%= lf.number_field :quantity %></td>
      </tr>
    <% end %>
  </table>
  <div class="row">
    <label>Yazdırma Şablonu</label>
    <%= f.select(:invoice_style_id, @invoice_styles.collect {|s| [s.name, s.id]}) %>
  </div>
    <div class="actions">
      <%= f.submit "#{f.object.new_record? ? 'Oluştur' : 'Güncelle'}" %>
    </div>
<% end %>

<script>
    window.onload = setVars();
</script>

app/views/invoices/edit.html.erb
<div class="main_header">
  <h2>Fatura Düzenle</h2>
  <div class="page_menu">
    <%= link_to 'Geri', invoices_path, :class => 'btn-default' %>
    <%= link_to 'Görüntüle', @invoice, :class => 'btn-info' %>
    <%= link_to 'Sil', @invoice, method: :delete, :class => 'btn-danger', data: { confirm: 'Emin misiniz?' } %>
  </div>
</div>
<div class="main_form">
  <%= render 'form' %>
  <%= button_to 'İptal', invoices_path, :method => :get, :class => 'cancel_button' %>
</div>

app/views/invoices/index.html.erb
<div class="main_header">
  <h2>Faturalar</h2>
  <div class="page_menu"><%= link_to '+ Yeni', new_invoice_path, :class => 'btn-success' %></div>
</div>

<p id="notice"><%= notice %></p>

<table class="data">
  <thead>
    <tr>
      <th>Tarih</th>
      <th>Zaman</th>
      <th>Müşteri</th>
      <th>Toplam</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr class="<%= cycle('odd_row', 'even_row') %>">
        <td><%= invoice.date %></td>
        <td><%= invoice.time.strftime('%H:%M') %></td>
        <td><%= (invoice.customer)? invoice.customer.name : '' %></td>
        <td><%= invoice.general_total %></td>
        <td class="actions">
            <%= link_to 'Göster', invoice %>
            <%= link_to 'Düzenle', edit_invoice_path(invoice) %>
            <%= link_to 'Sil', invoice, method: :delete, data: { confirm: 'Emin misiniz?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invoices/new.html.erb
<div class="main_header">
  <h2>Yeni Fatura</h2>
  <div class="page_menu">
    <%= link_to 'Geri', invoices_path, :class => 'btn-default' %>
  </div>
</div>
<div class="main_form">
  <%= render 'form' %>
  <%= button_to 'İptal', invoices_path, :method => :get, :class => 'cancel_button' %>
</div>

app/views/invoices/show.html.erb
<div class="main_header">
  <h2>Fatura</h2>
  <div class="page_menu">
    <%= link_to 'Geri', invoices_path, :class => 'btn-default' %>
    <%= link_to 'Yazdır', print_invoice_path(@invoice), :class => 'btn-default', :data => {turbolinks: false} %>
    <%= link_to 'Düzenle', edit_invoice_path(@invoice), :class => 'btn-warning' %>
    <%= link_to 'Sil', @invoice, method: :delete, :class => 'btn-danger', data: { confirm: 'Emin misiniz?' } %>
  </div>
</div>

<p id="notice"><%= notice %></p>

<div class="main_info">
  <p>
    <strong>Tarih:</strong>
    <span><%= @invoice.date %></span>
  </p>
  <p>
    <strong>Zaman:</strong>
    <span><%= @invoice.time.strftime('%H:%M') %></span>
  </p>
  <p>
    <strong>Müşteri:</strong>
    <span><%= link_to @invoice.customer.name, @invoice.customer %></span>
  </p>
  <p>
    <strong>Satır Öğeleri:</strong>
    <table class="line_items">
        <tr>
          <th>Ürün</th>
          <th>Adet</th>
          <th>Birim Fiyatı</th>
          <th>Tutar</th>
        </tr>
        <% @invoice.line_items.each do |line_item| %>
          <tr class="<%= cycle('odd_row', 'even_row') %>">
            <td><%= link_to line_item.product.description, line_item.product %></td>
            <td><%= line_item.quantity %></td>
            <td><%= line_item.product.unit_price %></td>
            <td><%= line_item.total %></td>
          </tr>
        <% end %>
    </table>
  </p>
  <p>
    <strong>Ara Toplam:</strong>
    <span><%= @invoice.sub_total %></span>
  </p>
  <p>
    <strong>Vergi Oranı:</strong>
    <span><%= '%' + @invoice.tax_rate.to_s %></span>
  </p>
  <p>
    <strong>Vergi Miktarı:</strong>
    <span><%= @invoice.tax_amount %></span>
  </p>
  <p>
    <strong>Genel Toplam:</strong>
    <span><%= @invoice.general_total %></span>
  </p>
  <p>
    <strong>Yazdırma Şablonu:</strong>
    <span><%= link_to @invoice.invoice_style.name, @invoice.invoice_style %></span>
  </p>
</div>