config/routes.rb
Rails.application.routes.draw do
  root 'invoices#index'
  resources :invoices
  resources :products
  resources :customers
  resources :invoice_styles

  get 'invoices/:id/print_pdf', to: "invoices#print_pdf", as: "print_invoice"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions, only: [:create, :destroy]

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :name, presence: true
  has_many :invoices
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Müşteri başarıyla oluşturuldu.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Müşteri başarıyla güncellendi.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Müşteri başarıyla silindi.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :address, :tax_office, :tax_office_no)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<% if @customer.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h4>
      <ul>
        <% @customer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for(@customer) do |f| %>
  <div class="row">
    <label>İsim</label>
    <%= f.text_field :name %>
  </div>
  <div class="row">
    <label>Adres</label>
    <%= f.text_area :address %>
  </div>
  <div class="row">
    <label>Vergi Dairesi</label>
    <%= f.text_field :tax_office %>
  </div>
  <div class="row">
    <label>Vergi Dairesi Numarası</label>
    <%= f.text_field :tax_office_no %>
  </div>
  <div class="actions">
      <%= f.submit "#{f.object.new_record? ? 'Oluştur' : 'Güncelle'}" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="main_header">
  <h2>Müşteri Düzenle</h2>
  <div class="page_menu">
    <%= link_to 'Geri', customers_path, :class => 'btn-default' %>
    <%= link_to 'Görüntüle', @customer, :class => 'btn-info' %>
    <%= link_to 'Sil', @customer, method: :delete, :class => 'btn-danger', data: { confirm: 'Emin misiniz?' } %>
  </div>
</div>
<div class="main_form">
    <%= render 'form' %>
    <%= button_to 'İptal', customers_path, :method => :get, :class => 'cancel_button' %>
</div>

app/views/customers/index.html.erb
<div class="main_header">
    <h2>Müşteriler</h2>
    <div class="page_menu">
      <%= link_to '+ Yeni', new_customer_path, :class => 'btn-success' %>
    </div>
</div>

<p id="notice"><%= notice %></p>

<table class="data">
  <thead>
    <tr>
      <th>İsim</th>
      <th>Adres</th>
      <th nowrap="nowrap">Vergi Dairesi</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr class="<%= cycle('odd_row', 'even_row') %>">
        <td><%= customer.name %></td>
        <td><%= customer.address %></td>
        <td><%= customer.tax_office %></td>
        <td class="actions">
          <%= link_to 'Göster', customer %>
          <%= link_to 'Düzenle', edit_customer_path(customer) %>
          <%= link_to 'Sil', customer, method: :delete, data: { confirm: 'Emin misiniz?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
<div class="main_header">
  <h2>Yeni Müşteri</h2>
  <div class="page_menu">
    <%= link_to 'Geri', customers_path, :class => 'btn-default' %>
  </div>
</div>
<div class="main_form">
    <%= render 'form' %>
    <%= button_to 'İptal', customers_path, :method => :get, :class => 'cancel_button' %>
</div>

app/views/customers/show.html.erb
<div class="main_header">
  <h2>Müşteri</h2>
  <div class="page_menu">
    <%= link_to 'Geri', customers_path, :class => 'btn-default' %>
    <%= link_to 'Düzenle', edit_customer_path(@customer), :class => 'btn-warning' %>
    <%= link_to 'Sil', @customer, method: :delete, :class => 'btn-danger', data: { confirm: 'Emin misiniz?' } %>
  </div>
</div>

<p id="notice"><%= notice %></p>

<div class="main_info">
  <p>
    <strong>İsim:</strong>
    <span><%= @customer.name %></span>
  </p>
  <p>
    <strong>Adres:</strong>
    <span><%= @customer.address %></span>
  </p>
  <p>
    <strong>Vergi Dairesi:</strong>
    <span><%= @customer.tax_office %></span>
  </p>
  <p>
    <strong>Vergi Dairesi No:</strong>
    <span><%= @customer.tax_office_no %></span>
  </p>
</div>