config/routes.rb
Rails.application.routes.draw do
  root 'invoices#index'
  resources :invoices
  resources :products
  resources :customers
  resources :invoice_styles

  get 'invoices/:id/print_pdf', to: "invoices#print_pdf", as: "print_invoice"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions, only: [:create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>FaturaYaz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
  <div id="header">
    <div id="logo"><%= link_to 'Fatura Yaz', root_path %></div>
    <div id="menu">
      <%= link_to 'Faturalar', invoices_path %>
      <%= link_to 'Müşteriler', customers_path %>
      <%= link_to 'Ürünler', products_path %>
      <a class="dropdown-button" href="javascript:void(0)" onclick="toggleDropdownMenu()">&#9776</a>
      <div class="dropdown-content" style="display: none;">
        <%= link_to 'Fatura Şablonları', invoice_styles_path %>
        <%= link_to "Çıkış", logout_path, id: "sign_out" %>
      </div>
    </div>
  </div>
  <div id="main">
    <%= yield %>
  </div>
  <div id="footer">
    Fatura Yaz | © 2014
  </div>
</div>
</body>
</html>